version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: amohmad
      MYSQL_DATABASE: prodra
    ports:
      - "3306:3306"

  backend:
    build: ./
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
