# Generated by Django 4.2.17 on 2024-12-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.CharField(default='00:00', max_length=32),
        ),
    ]
